### ISSUE TITLE
Is this working for you?

### ISSUE THREAD

**Issue by STRML** [tuvistavie/fish-kubectl#3]
It appears [this line](https://github.com/tuvistavie/fish-kubectl/blob/c81dfa36c1fd8862c3bd3d264d93ef14924b145a/completions/kubectl.fish#L68) is a reference error and should be:

`for i in (__kubectl_resources --no-prefix pods)` 

Aside from that, have you gotten this to meaningfully work for autofilling pods? I'm impressed at how complete it is, but https://github.com/evanlucas/fish-kubectl-completions/blob/master/kubectl.fish seems to have fewer issues.

**Comment by danhper** [comment]
Hi, thanks for reporting.
Indeed, I had a few local changes I forgot to push, sorry for that.
It should now be fixed, and provide proper completion even when `--namespace` is given.
